
[weapons]

	[weapons.m95]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 245000

	[weapons.ai_awp]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 204800

	[weapons.scar_h]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 155623

	[weapons.hk_g3]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 154770

	[weapons.db_long]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 141512

	[weapons.db_short]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 141512

	[weapons.m249]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 114073

	[weapons.sks_tactical]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 113512

	[weapons.rpk]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 105800

	[weapons.deagle]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 105800

	[weapons.m16a1]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 102152

	[weapons.deagle_golden]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 99331

	[weapons.ak47]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 96800

	[weapons.vector45]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 95207

	[weapons.ump45]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 90506

	[weapons.m16a4]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 84050

	[weapons.m4a1]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 83809

	[weapons.aa12]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 80000

	[weapons.rpg7]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 80000

	[weapons.hk_mp5a5]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 77356

	[weapons.cz75]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 74756

	[weapons.uzi]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 64800

	[weapons.glock_17]
		#How long this weapon will take to research at the Research Table; Provided in Game Ticks i.e 1200tick == 1min
		#Range: > 0
		"research time" = 31250

[ammo]

	[ammo.9mm]
		#How long this ammo type will take to research at the Research Table; Provided in Game Ticks; i.e 1200tick == 1min
		#Range: > 0
		"research time" = 13417

	[ammo.12g]
		#How long this ammo type will take to research at the Research Table; Provided in Game Ticks; i.e 1200tick == 1min
		#Range: > 0
		"research time" = 7454

	[ammo.30_06]
		#How long this ammo type will take to research at the Research Table; Provided in Game Ticks; i.e 1200tick == 1min
		#Range: > 0
		"research time" = 1000000

	[ammo.45acp]
		#How long this ammo type will take to research at the Research Table; Provided in Game Ticks; i.e 1200tick == 1min
		#Range: > 0
		"research time" = 3750

	[ammo.46x30]
		#How long this ammo type will take to research at the Research Table; Provided in Game Ticks; i.e 1200tick == 1min
		#Range: > 0
		"research time" = 1000000

	[ammo.50ae]
		#How long this ammo type will take to research at the Research Table; Provided in Game Ticks; i.e 1200tick == 1min
		#Range: > 0
		"research time" = 5500

	[ammo.50bmg]
		#How long this ammo type will take to research at the Research Table; Provided in Game Ticks; i.e 1200tick == 1min
		#Range: > 0
		"research time" = 16406

	[ammo.58x42]
		#How long this ammo type will take to research at the Research Table; Provided in Game Ticks; i.e 1200tick == 1min
		#Range: > 0
		"research time" = 1000000

	[ammo.68x51fury]
		#How long this ammo type will take to research at the Research Table; Provided in Game Ticks; i.e 1200tick == 1min
		#Range: > 0
		"research time" = 1000000

	[ammo.308]
		#How long this ammo type will take to research at the Research Table; Provided in Game Ticks; i.e 1200tick == 1min
		#Range: > 0
		"research time" = 4456

	[ammo.338]
		#How long this ammo type will take to research at the Research Table; Provided in Game Ticks; i.e 1200tick == 1min
		#Range: > 0
		"research time" = 10500

	[ammo.357mag]
		#How long this ammo type will take to research at the Research Table; Provided in Game Ticks; i.e 1200tick == 1min
		#Range: > 0
		"research time" = 4781

	[ammo.556x45]
		#How long this ammo type will take to research at the Research Table; Provided in Game Ticks; i.e 1200tick == 1min
		#Range: > 0
		"research time" = 3414

	[ammo.762x25]
		#How long this ammo type will take to research at the Research Table; Provided in Game Ticks; i.e 1200tick == 1min
		#Range: > 0
		"research time" = 1000000

	[ammo.762x39]
		#How long this ammo type will take to research at the Research Table; Provided in Game Ticks; i.e 1200tick == 1min
		#Range: > 0
		"research time" = 4200

	[ammo.762x54]
		#How long this ammo type will take to research at the Research Table; Provided in Game Ticks; i.e 1200tick == 1min
		#Range: > 0
		"research time" = 1000000

